### ISSUE TITLE
Workflow collector: runtime error, SIGSEGV

### ISSUE THREAD

**Issue by rissson** [promhippie/github_exporter#216]
Hi,

We recently are encountering the following error:

```
{"date":"20230607","go":"go1.20.4","level":"info","msg":"Launching GitHub Exporter","revision":"1c08846","ts":"2023-06-08T12:16:41.872661782Z","version":"1c08846"}
{"addr":"0.0.0.0:9504","level":"info","msg":"Starting metrics server","ts":"2023-06-08T12:16:41.874326114Z"}
{"address":"[::]:9504","level":"info","msg":"Listening on","ts":"2023-06-08T12:16:41.874865788Z"}
{"address":"[::]:9504","http2":false,"level":"info","msg":"TLS is disabled.","ts":"2023-06-08T12:16:41.874883864Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x553c54]

goroutine 35 [running]:
github.com/promhippie/github_exporter/pkg/exporter.(*WorkflowCollector).pagedRepoWorkflows(0x4000296420, {0x833f80, 0x40003aec30}, {0x4000424540, 0xb}, {0x4000424520, 0x9})
       /home/runner/work/github_exporter/github_exporter/pkg/exporter/workflow.go:252 +0x264
github.com/promhippie/github_exporter/pkg/exporter.(*WorkflowCollector).repoWorkflows(0x4000296420)
       /home/runner/work/github_exporter/github_exporter/pkg/exporter/workflow.go:206 +0x9d4
github.com/promhippie/github_exporter/pkg/exporter.(*WorkflowCollector).Collect(0x4000296420, 0x4000304758?)
       /home/runner/work/github_exporter/github_exporter/pkg/exporter/workflow.go:87 +0x40
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
       /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.15.1/prometheus/registry.go:455 +0xd8
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
       /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.15.1/prometheus/registry.go:466 +0x4d8
```

Our configuration:
```
GITHUB_EXPORTER_APP_ID: "0123456"
GITHUB_EXPORTER_COLLECTOR_RUNNERS: "true"
GITHUB_EXPORTER_COLLECTOR_WORKFLOWS: "true"
GITHUB_EXPORTER_INSTALLATION_ID: "0123456"
GITHUB_EXPORTER_ORG: "myorg"
GITHUB_EXPORTER_REPO: "myorg/*"
```

Our version: 2.2.0

It seems that `resp` is nil around here https://github.com/promhippie/github_exporter/blob/master/pkg/exporter/workflow.go#L252

Let me know if you need any additional information

**Comment by tboerger** [comment]
With https://github.com/promhippie/github_exporter/releases/tag/v2.2.1 this issue should be resolved.

**Comment by rissson** [comment]
I can confirm the issue is resolved on our side. Thanks for the swift fix!

**Comment by dhawalseth** [comment]
After using this version, I get past the nil pointer error but still run into:
```
│ level=error ts=2023-06-09T21:49:05.77855249Z collector=repo msg="Failed to fetch repos" name=org_name/* err="context deadline exceeded"             │
```
We do have a lot of repos under this org (16K+)
