### ISSUE TITLE
The program crashes with SIGSEGV error 

### ISSUE THREAD

**Issue by SokoloffA** [promhippie/github_exporter#49]
When I run the program it successfully started:
```
GITHUB_EXPORTER_TOKEN=XXX...XXX GITHUB_EXPORTER_REPO=flacon/flacon GITHUB_EXPORTER_WEB_ADDRESS=0.0.0.0:9504 ./github_exporter
{"date":"20201117","go":"go1.14.2","level":"info","msg":"Launching GitHub Exporter","revision":"2cb1c95","ts":"2021-04-16T22:02:22.418190294Z","version":"1.0.0"}
{"addr":"0.0.0.0:9504","level":"info","msg":"Starting metrics server","ts":"2021-04-16T22:02:22.418362723Z"}
```
But when I open URL http://192.168.XX.YY:9504/metrics, the program crashes
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x95f6ea]

goroutine 46 [running]:
github.com/promhippie/github_exporter/pkg/exporter.(*RepoCollector).Collect(0xc0000ce420, 0xc0000ae960)
	/drone/src/pkg/exporter/repo.go:311 +0xe3a
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/srv/app/pkg/mod/github.com/prometheus/client_golang@v1.8.0/prometheus/registry.go:444 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/srv/app/pkg/mod/github.com/prometheus/client_golang@v1.8.0/prometheus/registry.go:536 +0xe36
```

---

* Program - release [github_exporter-1.0.0-linux-amd64](https://github.com/promhippie/github_exporter/releases/download/v1.0.0/github_exporter-1.0.0-linux-amd64)
* OS: Debian GNU/Linux 10 (buster)

**Comment by tboerger** [comment]
Looks like the AllowRebaseMerge attribute is not present for some repo of you... Maybe I should add a condition to all attributes provided as a pointer :(

**Comment by SokoloffA** [comment]
> Maybe I should add a condition to all attributes provided as a pointer

To be honest, I didn't look at the project code and I didn't understand what you mean. I don't know which attributes provided as a pointer, but I believe that all pointers should be checked.  

P.S. The repository has the "Allow rebase merging" checked.

**Comment by tboerger** [comment]
Currently we got issues with the CI system, as a temporary workaround I have updloaded the binaries including the fix to https://dl.webhippie.de/temporary-github-exporter/, feel free to try out the fixed binaries until I can get into moving the CI system to get rid of the cloud.drone.io issues we are currently facing.

I will keep this issue open till I have been able to merge the fix and a proper release have been rolled.

**Comment by tboerger** [comment]
When the master branch build finishes I will tag a new release v1.0.1. Thanks for the report.

**Comment by tboerger** [comment]
With https://drone.webhippie.de/promhippie/github_exporter/5 you will see the release v1.0.1 pretty soon which resolves your problem.
